### ISSUE TITLE
Feedback on the first prototype

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#1]
@hupili - 

Just a collection of ad hoc feature requests and thoughts. We can have discussions down the thread and redirect actionable items to other issues to followup.

- [x] Slug: I prefer to add: 1) a prefix to not clutter with other parts of the site (non-blog ones); 2) date string before keyword string for quick sorting.
- [x] Needs to test special pages: i.e. those self-contained pack of HTML+CSS+JS, which is not generated from post markdown source.
- [x] Maybe fontsize is too large on smaller screens.
- [x] Test pagination
- [x] Filter -- Generate different post list according to: 1) language (say we write in en_US, zh_HK, zh_CN); 2) category; 3) tag
- [x] Sort -- Generate different post list according to: 1) date; 2) category
- [x] After enabling the above functionality, the homepage defaults to English + reverse chronological
- [x] Generate RSS/ Atom feeds. 1) Different feeds for different languages; 2) a feed for all languages.
- [x] Maybe we need to put the blog under /blog/? My understanding: The current blog.initiumlab.com is for testing purpose and the whole site (portofolio + blog) will be put under initiumlab.com.
- [x] Newsletter subscription entry-point
- [x] More sites for the social share bar.
- [x] Generate QR Code for WeChat.
- [x] Google Analytics (needs to add to page framework; should also work with special pages)
- [x] tag cloud, e.g. http://blog.hupili.net/tags.html#railway-ref

**Comment by andyshuxin** [comment]
## A. High Priority (Would rather delay launching for them)
- [ ] Slug:
    - [ ] Determine a prefix
    - [ ] add date string before keyword string for quick sorting
- [ ] Add newsletter subscription entry-point
- [ ] Set the root entry to initiumlab.com, and put the blog under /blog/
- [ ] Generate RSS/ Atom feeds for all content

## B. Intermediate Priority (Maybe next week)

- [ ] Basic adaptation for mobile screens
- [ ] Test special pages, which should bypass markdown rendering
- [ ] Set the homepage default to English + reverse chronological
- [ ] RSS Feed for each language

## C. Low Priority (Within this month)

- [ ] Add more sites for the social share bar
      - [ ] Determine desired share destinations
      - [ ] Generate QR Code for WeChat.
- [ ] Filter -- Generate different post list according to: 1) language (say we write in en_US, zh_HK, zh_CN); 2) category; 3) tag
- [ ] Sort -- Generate different post list according to: 1) date; 2) category

**Comment by hupili** [comment]
>  Set the homepage default to English + reverse chronological

Not so important. Let's focus on building content for now and freely mix English or Chinese. Mark resolved.

**Comment by hupili** [comment]
> Filter -- Generate different post list according to: 1) language (say we write in en_US, zh_HK, zh_CN); 2) category; 3) tag

currently partially solved by tag. Skip

**Comment by hupili** [comment]
> Sort -- Generate different post list according to: 1) date; 2) category

Not so important for now.
