### ISSUE TITLE
Add alt to the images on our site

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#10]
Need to:

* Scan all the pages #20 
* Add this to workflow #26

**Comment by andyshuxin** [comment]
@hupili I manually scan the homepage and "Data Journalism for the Blind" article and added alts for every image.

**Comment by hupili** [comment]
Memo: we need to document a online checklist for each articles; "Scan alt images" will be one item of the checklist.

**Comment by hupili** [comment]
Checklist discussion: #26

**Comment by andyshuxin** [comment]
@hupili Shall we close this issue and discuss the topic on the "checklist" issue and the "automatic checking" issue?

**Comment by hupili** [comment]
Yes. Updated redirect pointers into the main post.
