### ISSUE TITLE
Hexo expects <more> delimiter to generate the excerpt for blog list

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#117]
Current situation:

* http://initiumlab.com : this list will use the meta info, i.e. `description`, we put on YAML header
* http://initiumlab.com/blog/    : seems this one only uses `<more>` delimiter  (if there is no this delimiter, the excerpt is empty).

**Comment by hupili** [comment]
@andyshuxin if this is expected behaviour, we need to add the caveat reminder into our workflow

**Comment by hupili** [comment]
Reference issue: https://github.com/initiumlab/initiumlab.com/pull/115

**Comment by andyshuxin** [comment]
@hupili What excerpt are your referring to? WeChat?

**Comment by hupili** [comment]
I mean the excerpted text under title. Say 

The text on homepage: (from `description`)

> We tested a 3D-printed LegcoMatrix infographic with the first blind user Chong Chan Yau, president of Hong Kong Blind Union. The solution almost worked and we got valuable advices from him on how to further polish the work.

The text on blog list: (from `<more>` tag; if there no `<more>` tag, this paragraph will not exist)

> Based on vote records of 2921 motions of current Hong Kong Legislative Council meetings, Initium Lab analyzed the voting patterns of 70 legislators in Legco Matrix project. For visualization, we made a heat map of 70 rows by 70 columns, with the brightness of each cell representing supportiveness from one voter towards one motion mover (in terms of the percentage of supporting votes).

**Comment by andyshuxin** [comment]
@hupili Oh yes, this is the intended behaviour. It used to be same (both displaying `description`). But it doesn't look good as the blog list would be identical to the front page.
I'll mention it in README.

**Comment by hupili** [comment]
Noted. We also need to add a note to the workflow, i.e.

> Check whether `<more>` tag exists before publishing

**Comment by andyshuxin** [comment]
@hupili Expand the grunt scan perhaps?

**Comment by hupili** [comment]
:+1: That should work

**Comment by andyshuxin** [comment]
Implemented with https://github.com/initiumlab/initiumlab.com/commit/73eefcd86ba92a8973455c688c641b36843d2900

Now can use `grunt scan:summaryTag` to check for `<!-- more -->`

**Comment by andyshuxin** [comment]
Workflow updated with https://github.com/initiumlab/initiumlab.com/commit/4a5b3cb8d61f26a950ef29c07d390c7f0c16e871
