### ISSUE TITLE
Portofolio block management

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#119]
Currently the portofolio block on home page is managed in the customised next-theme. It is better to put all the content in this repo so that it is separated from the style.

**Comment by andyshuxin** [comment]
Implemented with https://github.com/initiumlab/hexo-theme-next/commit/64bf84e8ed2d6659e1e49e51611125752fdb1afc and contents are migrated with https://github.com/initiumlab/initiumlab.com/commit/bcf810227c629c969a72aa72dd58d4e5f9c9d839 and https://github.com/initiumlab/initiumlab.com/commit/8559e2eaa9da0539b14b660c4c87efe221977676
