### ISSUE TITLE
Fix quote about "absence of evidence is not evidence of absence"

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#121]
From a Bayesian point of view, it really is.

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/93b9bc300b7d1583f3b6b972302defaac429bfa7

**Comment by Kateliuxue** [comment]
@andyshuxin  So far so good. This issue can be closed.
