### ISSUE TITLE
Staging server: Erroneous path due to timezone setting

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#128]
@hupili @frankinit @yyfjmb 

The staging server's timezone is UTC. Hexo seems to assume use system timezone to interpret markdown source file time stampings.

I've create a branch called `timezone-test` to demonstrate a weird behaviour:

In `source/_posts`, there are two files,
`20151029-early.md` and
`20151029-late.md`
They have the same filename-timestamp of `20151029`, but their timestamp in the markdown are different, the early one is set at `2015-10-29 07:00:00`, while the late one is `2015-10-29 09:00:00`

`20151029-late.md` will be compiled into `public/blog/20151029-late/index.html`, as expected.
But `20151029-early.md` will become `public/blog/20151028-early/index.html` (notice the date).

My hypothesis is that this `20151029-early`, being published on `2015-10-29 07:00:00`, is assumed to be published in UTC+8, and calculated to be `20151028 23:00:00`, in UTC+0, the system timezone.

I expect that setting the system timezone to UTC+8 will fix such issue.

**Comment by andyshuxin** [comment]
@hupili @frankinit Would it make sense to set the staging server to UTC+8?

**Comment by hupili** [comment]
Yes. Please set to `UTC+8`

**Comment by andyshuxin** [comment]
@frankinit Can you set the timezone on the staging server to `UTC+8`?

**Comment by andyshuxin** [comment]
I've set the timezone to UTC+8

**Comment by hupili** [comment]
@andyshuxin can you outline the steps for @frankinit  future reference, thanks

**Comment by andyshuxin** [comment]
@hupili @frankinit 
It's rather straightforward. Just
```bash
sudo dpkg-reconfigure tzdata
```
Then you get a GUI to set timezone.

To check the current timezone, use
```
date
```

**Comment by frankinit** [comment]
Thanks @andyshuxin. I applied this on CKAN server.
