### ISSUE TITLE
Wording on http://home.initiumlab.com/blog/20150901-data-journalism-for-the-blind/

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#13]
又
沒有替代說明

Alt

Spacing around English characters

**Comment by frankinit** [comment]
「絃樂」應為「弦樂」？

**Comment by andyshuxin** [comment]
@frankinit 管**絃**，弓**弦**，不是一個字，近代歸於弦。是否立爲內部規範，可以討論。
參見：<http://www.fhk.ndu.edu.tw/mediafile/833/fdownload/489/828/2014-4-24-10-0-7-828-nf1.pdf>

**Comment by andyshuxin** [comment]
Close the issue as the obvious flaws have been removed.
We can continue to discuss orthographical decisions.
