### ISSUE TITLE
Update About Page with technology used

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#19]
@yyfjmb Please update the about page (at source/about/index.md)  <http://home.initiumlab.com/about/> with technologies you used for the website, such as css libraries, if any.
You can put the information under *Credits* section.

**Comment by andyshuxin** [comment]
@yyfjmb You seem to be working on this. If you're done, you can @me here.

**Comment by yyfjmb** [comment]
I didn't really use any css libraries. I wanted to use hover.css at first, end up with self-reliance.

**Comment by yyfjmb** [comment]
If new technologies are used, I'll add them there. @andyshuxin
