### ISSUE TITLE
A solution to host images

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#2]
Link: http://home.initiumlab.com/blog/20150901-data-journalism-for-the-blind/

Image: 

<img width="750" alt="screen shot 2015-09-03 at 9 37 56 pm" src="https://cloud.githubusercontent.com/assets/1227160/9659644/1a74552c-5284-11e5-9335-563a6d159aa9.png">

We need a solution for image hosting:

1. Use 3rd party image hosting services
2. Check in the images into repo

If the 2nd is used, we need to design a proper dir structure and naming convention for the images.

**Comment by andyshuxin** [comment]
We are current going with solution 2, putting images under the folder of the same name as the Markdown file.
For example, the images for **20150903-data-journalism-for-the-blind.md** is stored under "20150903-data-journalism-for-the-blind" directory.

This folder can be created automatically by hexo if one create a new entry with
```
hexo new "title"
```

**Comment by hupili** [comment]
Solution 2 should be enough for now. The use of abs path in [post source code](https://raw.githubusercontent.com/initiumlab/initiumlab.com/master/source/_posts/20150903-data-journalism-for-the-blind.md) may cause some inconvenience during migration. This should be low priority now.
