### ISSUE TITLE
In tag view, the header will cover the main content

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#23]
@yyfjmb 

![screen shot 2015-09-15 at 9 21 59 pm](https://cloud.githubusercontent.com/assets/233354/9877513/e8fd66c6-5bef-11e5-8b35-25d65039027c.png)

**Comment by andyshuxin** [comment]
duplicate: https://github.com/initiumlab/initiumlab.com/issues/24

**Comment by yyfjmb** [comment]
fixed
