### ISSUE TITLE
On a specific version of Firefox, the image is off

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#27]
It appears on Firefox 40.0.3, OSX 10.10, iMac 27 inch.
However, the bug does not appear on Firefox Developer Edition 42.0a2, same system.
Could be a isolated problem.
<http://home.initiumlab.com/blog/20150901-data-journalism-for-the-blind/>

![screen shot 2015-09-16 at 11 32 16 am](https://cloud.githubusercontent.com/assets/233354/9895861/07f75cea-5c67-11e5-92af-1e8cba94026a.png)

**Comment by yyfjmb** [comment]
fixed the problem. but find another firefox problem. can't load youtube flash.
![image](https://cloud.githubusercontent.com/assets/7417451/9899028/9c809314-5c89-11e5-8c59-c2d81a24c701.png)

**Comment by andyshuxin** [comment]
@yyfjmb Please pose an issue and @me. Also please list your browser version, OS versions, etc.
