### ISSUE TITLE
Meta information of posts

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#3]
Some information is needed in the YAML header; and also to be rendered in the page HTML

1. Author name

e.g. CODE4HK blog:
https://github.com/code4hk/blog/blob/gh-pages/_posts/2014-02-23-blog-is-up.md

This can be compiled to special HTML tags so we do not have to write author name in the body.

2. Author image?

Seems the current template supports author image, but we have not included one. Let check this function.

<img width="240" alt="screen shot 2015-09-03 at 9 43 25 pm" src="https://cloud.githubusercontent.com/assets/1227160/9659788/dc9254ec-5284-11e5-82b9-03c2bdddc0f4.png">

3. Category

Category is marked using the tag system. We need to add the category link in post template.

----------

Those are not high priority.

**Comment by andyshuxin** [comment]
The side-bar has been re-designed and we no longer show author image.
