### ISSUE TITLE
Style one markdown specifically

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#34]
"About" page needs special styling. Now, it's implemented with inline <div class='something>, which hackish.

**Comment by hupili** [comment]
Reference discussions:
https://github.com/initiumlab/initiumlab.com/commit/c7e7d576b6e2f88b83394f1a42b9b075baca522b#commitcomment-13265582

**Comment by hupili** [comment]
After checking with and without the `id=aboutpage` markup, I did not see much difference(only URL becomes blue?). If so, I weight standard over insignificant visual difference. This is also better for maintenance (occam's razor). 

@andyshuxin @yyfjmb

**Comment by hupili** [comment]
without:

<img width="739" alt="screen shot 2015-09-23 at 9 54 59 pm" src="https://cloud.githubusercontent.com/assets/1227160/10046866/d2c67cb8-623d-11e5-87ca-53a67934535b.png">

**Comment by hupili** [comment]
with:

<img width="752" alt="screen shot 2015-09-23 at 9 55 13 pm" src="https://cloud.githubusercontent.com/assets/1227160/10046873/dc642bc6-623d-11e5-91f5-be90e40a7393.png">

**Comment by hupili** [comment]
I think the stylisation of those links should go into the "next theme".

**Comment by andyshuxin** [comment]
I agree. I removed styles specific to the about page.
@yyfjmb You can now style all links with `themes/source/css/_custom/custom.styl`. I've added special rules for the home page so that they'll remain without underlines.

**Comment by andyshuxin** [comment]
Solution: don't style a markdown specifically. If needed, use HTML + CSS.

**Comment by hupili** [comment]
I once used `<link css` to style one markdown. Not recommended.
