### ISSUE TITLE
On iPhone, RSS Feed button opens podcast

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#36]

**Comment by andyshuxin** [comment]
@hupili @frankinit @Kateliuxue Switched to feedburner, which seems to work. Can you verify?
However, we might need a solution more proper for the long turn.

**Comment by frankinit** [comment]
good on my iPhone iOS 8

**Comment by frankinit** [comment]
New problem: cannot access feedburner from Mainland China.

**Comment by andyshuxin** [comment]
@hupili @frankinit @Kateliuxue I've switched back to the native feed, rather than feedburner. We can deal with this later.
