### ISSUE TITLE
Not responsive on small size desktop browsers

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#37]
Chrome, width 400px, attached:

<img width="512" alt="screen shot 2015-09-17 at 11 01 20 am" src="https://cloud.githubusercontent.com/assets/1227160/9923809/d191b3c4-5d2b-11e5-928b-ec3280947190.png">

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/initiumlab.com/commit/82bbb56a9b967e1b21d16a2d141c698d66b546f6. Now the mobile adjustments are applied as expected. Details are to be polished.
