### ISSUE TITLE
Side Bar Blocking Content

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#38]
<img width="1030" alt="screenshot 2015-09-17 at 11 44 47" src="https://cloud.githubusercontent.com/assets/13608119/9924396/a537abfc-5d31-11e5-8e61-ed265c2523d3.png">

http://initiumlab.com/blog/20150901-data-journalism-for-the-blind/

OS X 10.10.5 , Chrome 45, Macbook Pro Retina.

**Comment by yyfjmb** [comment]
I've tried to narrow the width of side-bar, then there's not enough space to show all content in the side bar. Maybe that's the reason why the sidebar is originally designed to push the content to the left.

**Comment by andyshuxin** [comment]
@yyfjmb How about make the sidebar half-transparent? Would that make sense?

**Comment by yyfjmb** [comment]
@andyshuxin tried but doesn't work
![image](https://cloud.githubusercontent.com/assets/7417451/9927879/a469eb4a-5d54-11e5-9877-aac31b671ccd.png)
texts are overlapped.

**Comment by andyshuxin** [comment]
The current solution is to use a narrow sidebar.
