### ISSUE TITLE
Style Discussion: Need a Space after Colon?

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#41]
<img width="85" alt="screenshot 2015-09-17 at 12 22 54" src="https://cloud.githubusercontent.com/assets/13608119/9924909/df15d114-5d36-11e5-9387-62d011f2e4f1.png">

Need a space after colon?

**Comment by andyshuxin** [comment]
@frankinit 
Hexo doesn't support tags with spaces very well. Path issues.
I do agree the colon doesn't look prominent in the tags and could be confusing.
I've changed colons to hyphens.

**Comment by andyshuxin** [comment]
We shall use hyphen for future tags.
