### ISSUE TITLE
Subscribe Button Not Aligned with Text Field

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#42]
![screenshot 2015-09-17 at 12 30 55](https://cloud.githubusercontent.com/assets/13608119/9925003/1f167f88-5d38-11e5-9201-9016bce2a376.png)

Zoom in: 
![screenshot 2015-09-17 at 12 34 32](https://cloud.githubusercontent.com/assets/13608119/9925028/7ea33fea-5d38-11e5-8cbe-a78c7d9ab99e.png)

Height difference.

Chrome 45, OS X 10.10.5.

**Comment by yyfjmb** [comment]
fixed @frankinit
