### ISSUE TITLE
Revamp the article 《可視化火了 盲人怎麼辦》

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#43]
1. 「笑聲」應為「小聲」
2. 聲音操縱變量中「長度」是否沒有解釋清楚？
3. 「我們不關注盲人，盲人可是會看我們」這句話有兩個用戶表示沒看懂
4. 「如果我們相信新聞機構不只是牟利的商業公司，而是承擔了社會責任，」的什麼？是否有語法問題？
5. 「而 非盲人」還是「而非 盲人」？容易斷錯句
6. 引用的標註格式是否要規範？

**Comment by andyshuxin** [comment]
All comments processed with editing. No formal citation format is decided upon.
