### ISSUE TITLE
Video Width Not Responsive Causing Different Behaviour on iOS 9 and iOS 8

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#44]
The Youtube video module is not responsive, causing different behaviour on iOS 9 and iOS 8, both need to improve.

### iOS 9, Safari, auto adjusted for video width, but text too small:

<img src="https://cloud.githubusercontent.com/assets/13608119/9925399/a102c524-5d3d-11e5-9e9d-1f9666df576b.PNG" height="600">
<br><br><br><br>

### iOS 8, Safari, auto adjusted for text, but video not fully shown:
<img src="https://cloud.githubusercontent.com/assets/13608119/9925405/ac8e6808-5d3d-11e5-99c1-4b46157cdc64.JPG" height="600">

**Comment by andyshuxin** [comment]
@frankinit Updated the markup. Can you confirm the status of the issue?

**Comment by frankinit** [comment]
@andyshuxin looks good now, both on iOS 8 and iOS 9.
