### ISSUE TITLE
Video broke down on Redmi's default browser

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#45]
When tested on Redmi, legco video works well on Chrome, but doesn't on Redmi's default browser.

**Comment by andyshuxin** [comment]
@Kateliuxue Can you check the status quo? A new approach is tried and upload onto staging server ( 192.168.1.6/initiumlab.com). The staging server is not accessible outside of our office, unless one channels it.

**Comment by frankinit** [comment]
Update: now this issue is fixed on the online version, but exists on the staging version. @andyshuxin @Kateliuxue

**Comment by andyshuxin** [comment]
@frankinit @Kateliuxue 
Seems fixed along the way. Not entirely sure which commit fixed this.
