### ISSUE TITLE
Search Results Point to Wrong Address (home.initiumlab.com)

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#47]
![screenshot 2015-09-17 at 13 57 11](https://cloud.githubusercontent.com/assets/13608119/9926028/38445672-5d44-11e5-9907-8ee938ce4734.png)
![screenshot 2015-09-17 at 13 57 27](https://cloud.githubusercontent.com/assets/13608119/9926031/3d2b5c08-5d44-11e5-8d79-4f7a9bb12e2c.png)

Search results point to wrong address.

**Comment by andyshuxin** [comment]
@frankinit Should have been fixed. Please check.
