### ISSUE TITLE
Navigation Buttons on Homepage are Larger than Those on Other Pages

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#48]
![screenshot 2015-09-17 at 15 13 40](https://cloud.githubusercontent.com/assets/13608119/9927184/f1f9cd4a-5d4e-11e5-946d-448a3c76d411.png)
When click these buttons on homepage and jump to another page, they suddenly became smaller.

**Comment by andyshuxin** [comment]
Fixed with the refactor https://github.com/initiumlab/initiumlab.com/commit/82bbb56a9b967e1b21d16a2d141c698d66b546f6
