### ISSUE TITLE
Unsafe warning if visited via HTTPS

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#49]
<img width="777" alt="screen shot 2015-09-17 at 3 25 34 pm" src="https://cloud.githubusercontent.com/assets/1227160/9927325/65a452be-5d50-11e5-852d-85a8313453e2.png">

**Comment by andyshuxin** [comment]
This is a GitHub issue right?

"Pages are served over HTTP, not HTTPS, so you shouldn't use them for sensitive transactions, like sending passwords or credit card numbers."

https://help.github.com/articles/what-are-github-pages/

**Comment by hupili** [comment]
We have enabled [flexible TLS](https://www.cloudflare.com/ssl) on CloudFlare. Needs to check why this does not work.

**Comment by hupili** [comment]
Enabled CloudFlare cloud for initiumlab.com . May come back to check later.

**Comment by hupili** [comment]
Should be OK now. Batch signed certificates are available.

<img width="764" alt="screen shot 2015-09-17 at 3 33 16 pm" src="https://cloud.githubusercontent.com/assets/1227160/9927489/8537fda0-5d51-11e5-84fe-9eb589c1d765.png">
