### ISSUE TITLE
Automatically embed special pages into a framework or inject template code

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#5]
For example, the whole site want to share the same tracking code. The tracking code had better be maintained in the framework, site-wise. We need to inject the tracking code into the special pages.

**Comment by andyshuxin** [comment]
It is implemented by added the desired code into
```
themes/next/layout/_layout.swig
```
Note: Swig is a template language generating HTML.

**Comment by andyshuxin** [comment]
The Google tracking is now added natively by the hexo engine, we don't even need to add the code manually.
For other customised JavaScript, we can use the method I mention above.

The homepage (index.html) bypasses render engines and therefore should be adjusted separately.
