### ISSUE TITLE
Credit Logo Designers 

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#52]
As per our convention, those who effectively contributed will be acknowledged, regardless whether their work can be seen in the final product or not. 

* For code contributor, the GH link suffices
* For other contributors, good convention is to open a `CONTRIBUTOR` file and list them there

We can credit the logo designers once the result is out.

**Comment by hupili** [comment]
Since we have `humans.txt`, we can add `Contributor` section there for simplicity.

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/initiumlab.com/commit/083043a8d6edbcf8f5461c014d794cb53b7ed227
@hupili
