### ISSUE TITLE
Support longer project title

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#56]
![screen shot 2015-09-17 at 5 39 17 pm](https://cloud.githubusercontent.com/assets/1227160/9930010/18403002-5d63-11e5-92fd-985799aba3d0.png)

**Comment by andyshuxin** [comment]
@yyfjmb Any plan to enlarge the showcase to accommodate such needs?

**Comment by andyshuxin** [comment]
Editors should use short headings for the moment.

**Comment by andyshuxin** [comment]
@andyshuxin Add warning to workflow

**Comment by andyshuxin** [comment]
Added with https://github.com/initiumlab/initiumlab.com/commit/e7ff0f928a8fb1ebf6f4d4f30fb5207432f23ef4
