### ISSUE TITLE
Enable comment 

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#59]

**Comment by andyshuxin** [comment]
Enabled with https://github.com/initiumlab/initiumlab.com/commit/894e9b1969d2f43dc476a3ed5b4609c9e412d1a4
Need testing. @Kateliuxue @frankinit

**Comment by frankinit** [comment]
Haven't deployed yet? I don't see comment box in staging and production site.

**Comment by andyshuxin** [comment]
@frankinit Should work now. Thanks.

**Comment by frankinit** [comment]
@andyshuxin 
Looks good!
Problem: 
<b> Blog Links in The Side Bar Points to Wrong URL "home.initiumlab.com/xxxx" </b>
![screenshot 2015-09-25 at 17 33 02](https://cloud.githubusercontent.com/assets/13608119/10097483/fcbc1b26-63ab-11e5-9981-a0c74f346a41.png)
