### ISSUE TITLE
The credits of our website

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#6]
1. the following block needs to be moved from template to about page:

<img width="294" alt="screen shot 2015-09-14 at 12 03 08 am" src="https://cloud.githubusercontent.com/assets/1227160/9837557/8745dba0-5a75-11e5-8500-90df11208a63.png">

2. on the about page, credit to visual design (Victoria) and frontend implementation (Andy)

3. on the about page, credit to the open source projects used here (maybe make a list including Hexo and NexT, MathJax, etc)

**Comment by andyshuxin** [comment]
@hupili Added credits on the about page.
<http://home.initiumlab.com/about/>

**Comment by hupili** [comment]
Added GH contributors link to the about page. 746d71aecd7ef0e5a28014d236169636ffb91c57

Should be OK. Let's continuously revise.

Related issue #7
