### ISSUE TITLE
Disable mailchimp; after the user click the subscribe button, tell them that it worked

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#62]

**Comment by andyshuxin** [comment]
Fixed by https://github.com/initiumlab/initiumlab.com/commit/135bb62ddb6e35eab71af4e73b5c457117526d90

@hupili I've deployed to staging. Can take a look.
Also, I've tested a few email address ending in @example.com, which should be recorded by backend but to be removed.

**Comment by hupili** [comment]
Nice. Close for now. We can optimise presentation later.
