### ISSUE TITLE
Search Box Exceeding the Right the Right Edge of Page

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#63]
![screenshot 2015-09-18 at 11 06 33](https://cloud.githubusercontent.com/assets/13608119/9951174/805800a6-5df5-11e5-9e11-cb789e8a5fc9.png)

Search box exceeds right edge.

Chrome 45, OS X 10.10.5, Macbook Pro Retina.

**Comment by andyshuxin** [comment]
@yyfjmb Please take a look

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/fbc89004ad34601e69f29c65b2f074e9cf92af64

**Comment by frankinit** [comment]
Fix confirmed.
