### ISSUE TITLE
Use smaller sized images for the portofolio thumbnails

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#65]
I mean smaller size in Bytes. When network is slow, we see loading effect of some images, e.g. the legco one.

**Comment by yyfjmb** [comment]
fixed @hupili  commit@4b58fb0cbf4671ad0aef7bfb3fb145ddfb6ea63a

**Comment by andyshuxin** [comment]
@yyfjmb As a side note, are you aware of the ```srcset``` attribute of ```<img>```?
You can actually contain multiple ```src``` attributes for different viewport sizes.
<http://www.html5rocks.com/en/mobile/high-dpi/#toc-srcset>

**Comment by hupili** [comment]
No wonder I can not visit the link, the commit link has error. Correct one followed:
https://github.com/initiumlab/initiumlab.com/commit/4b58fb0cbf4671ad0aef7bfb3fb145ddfb6ea63a
