### ISSUE TITLE
The RSS hover effect is not uniformly applied to both icon and text

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#66]
<img width="74" alt="screen shot 2015-09-21 at 12 39 16 am" src="https://cloud.githubusercontent.com/assets/1227160/9981906/16b8a8bc-5ffd-11e5-88d6-edcd916e1041.png">
<img width="66" alt="screen shot 2015-09-21 at 12 39 13 am" src="https://cloud.githubusercontent.com/assets/1227160/9981907/16c2f718-5ffd-11e5-930a-2e5a619d86a8.png">

**Comment by andyshuxin** [comment]
The logo is removed for simplicity. @hupili
