### ISSUE TITLE
Use yaml syntax for author and language markup

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#67]

**Comment by andyshuxin** [comment]
Added language markup. Not really useful at the moment.

**Comment by hupili** [comment]
We can also:

* Add `thumbnail` field in the YAML header
* Render a `hidden` thumbnail image at the beginning of the doc via template. --- better rendering at WeChat sharing
* Render an `og` tag for this thumbnail image. --- better for rendering for FB and many supported sites.

**Comment by andyshuxin** [comment]
@hupili What's the issue with the current Facebook thumbnail?

**Comment by andyshuxin** [comment]
@hupili Customized `og:image` is implemented by modifying hexo plugin codes.
The outcome is http://192.168.1.6/initiumlab.com/blog/20150901-data-journalism-for-the-blind/
It has customized `og:image`, being
```
<meta property="og:image" content="http://initiumlab.com/blog/blog/20150901-data-journalism-for-the-blind/news-related-disabilities.jpg">
```
specified by YAML of
```
thumbnail: /blog/20150901-data-journalism-for-the-blind/news-related-disabilities.jpg
```

I'm asking Hexo people if this can be done in more clever ways:
https://github.com/hexojs/hexo/issues/1525

**Comment by hupili** [comment]
Need to add another field, `description` or `excerpt`. Render the text into a special non-display block. In the Weixin API, we can point the description to its inner text. In this way, the shared articles look better.

![850636862_794530742592000518](https://cloud.githubusercontent.com/assets/1227160/10244399/87dc547a-6931-11e5-9fae-0c228d0393a0.jpg)

**Comment by andyshuxin** [comment]
@hupili Description field is supported and reflects in the `description` field of HTML. I open another issue specifically for the WeChat excerpt issue: #113
