### ISSUE TITLE
Dual video deployment?

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#69]
@hupili
YouTube is blocked in Mainland China and I think we can't rely on it as the sole video source for our users.
How about keeping a copy on GitHub pages, serve it with <video>, and also maintain a YouTube channel to accumulate viewership? [The max size for GitHub is 1G](https://help.github.com/articles/what-is-my-disk-quota/) -- it'll take a while before reaching the limit.
For reference, the Legco video on staging server is served as local file via <video>.

**Comment by hupili** [comment]
Maybe open a channel on Youku? We can point the user to different sources at Frontend.

**Comment by andyshuxin** [comment]
@hupili Makes sense.

**Comment by andyshuxin** [comment]
Upload video to Youku and added a link to Jacakthon 3.

**Comment by andyshuxin** [comment]
We have set up YouTube and Youku accounts with the initiumlabeditor@gmail.com, to which we can upload videos. (Please ask Pili or me for sign-in details.)

At this moment, we have three video distribution channels
- gh-pages, displayed with <video>
- [YouTube](https://www.youtube.com/channel/UC6A8BFtKG3sRcExuOomA_tA)
- [Youku](http://i.youku.com/u/UMzIyNDgzODcwNA==)

**Comment by andyshuxin** [comment]
We have established channels on YouTube and Youku. Additionally, when the video is small, we put it in the repo itself.
This issue is considered closed.
