### ISSUE TITLE
Staging: Extra Scroll bar on windows.

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#71]
![default](https://cloud.githubusercontent.com/assets/14042060/10011305/bc721c9c-612a-11e5-9024-4a7ebb79255c.jpg)

**Comment by andyshuxin** [comment]
@Kateliuxue Can you list the browser? Also, do all browsers have such behaviour, or just one? (I'm guessing IE)

**Comment by Kateliuxue** [comment]
All browsers on Windows 8.1, including Chrome, Firefox & IE.

**Comment by andyshuxin** [comment]
We're not going to deal with this issue for the moment.
