### ISSUE TITLE
Staging: Video is Disabled on Home Page 

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#72]
<img width="873" alt="screenshot 2015-09-22 at 13 02 11" src="https://cloud.githubusercontent.com/assets/13608119/10011303/ba48df14-612a-11e5-92bf-c6d1ed76b1c2.png">

This video doesn't work. Neither on Windows nor on Mac.

**Comment by andyshuxin** [comment]
@frankinit Can you confirm whether it doesn't πlay altogether, or just the poster image is missing?

**Comment by frankinit** [comment]
@andyshuxin It is fine now. When I posted this issue, the Play Button of the video is disabled.

**Comment by andyshuxin** [comment]
@frankinit If it's OK, please close the issue.

**Comment by frankinit** [comment]
Fix confirmed.
