### ISSUE TITLE
Staging: An Image Not Shown on Home Page

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#73]
<img width="784" alt="screenshot 2015-09-22 at 13 01 55" src="https://cloud.githubusercontent.com/assets/13608119/10011341/2ed7f252-612b-11e5-8de3-1ec6da1c49d3.png">
<img width="865" alt="screenshot 2015-09-22 at 13 01 59" src="https://cloud.githubusercontent.com/assets/13608119/10011344/375c7bfa-612b-11e5-8752-34721d6d0931.png">

OS X 10.10.5, Chrome 45.

**Comment by andyshuxin** [comment]
@frankinit This is path-dependent. Can you provide the URL?

**Comment by frankinit** [comment]
@andyshuxin It does not recurrent now.

**Comment by andyshuxin** [comment]
@frankinit I think I fixed it around the same time you were doing the test

**Comment by andyshuxin** [comment]
@frankinit Please close the issue if it works now.
