### ISSUE TITLE
Staging: zoomed-in picture being placed in wrong place on windows.

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#74]
![default](https://cloud.githubusercontent.com/assets/14042060/10011350/4f0205fe-612b-11e5-9963-e10b60c9f433.jpg)

windows 8.1  pix 1600×900   Chrome

**Comment by andyshuxin** [comment]
@Kateliuxue Does this problem still exist? When you have time, please summon me to inspect the settings your computer. Thanks

**Comment by Kateliuxue** [comment]
It looks fine now. Shall we close this issue?

**Comment by andyshuxin** [comment]
@Kateliuxue I didn't specifically work on this issue. It might still pop up in the future. Let's deal with it then.
