### ISSUE TITLE
poster attribute of <video> is not processed by relativeRoot

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#77]
This is temporarily fixed by manually injecting 
```javascript
        .replace(/(poster=["'])\/(?!\/)/g, '$1'+relativeRoot)
```
into line 30 of  ```node_modules/grunt-relative/root/tasks/relative_root.js```.

**Comment by hupili** [comment]
@andyshuxin needs to maintain our own "hacked" repo and ask npm to refer to that repo. So it also works on other member's env.

**Comment by andyshuxin** [comment]
Done. Every developer, please ```git pull``` on your root and ```npm install``` to update your packages.
