### ISSUE TITLE
Staging: Email Subscribe Button Does Not Lead to a Confirm Message but a New Page

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#78]
<img width="460" alt="screenshot 2015-09-22 at 13 22 14" src="https://cloud.githubusercontent.com/assets/13608119/10011476/420c596a-612d-11e5-9f70-fe43896e050c.png">

Confusing behaviour.

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/b8afe3f4730d40cceb16c3a201951ecbe44f04ef.

**Comment by frankinit** [comment]
Thanks. Fix confirmed.
