### ISSUE TITLE
Staging: Email Subscribing Not Working

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#79]
10 Minutes ago I filled in my Gmail address and press Subscribe button. I am supposed to receive something, right?

Both on OS X 10.10.5 and Windows 8.1.

**Comment by andyshuxin** [comment]
@frankinit Did you see the success message?
Anyways, we haven't written the backend email processing, so actually it's expected that you receive nothing.
But you can confirm with Pili (who has access to our backend server) if your email is logged.

**Comment by frankinit** [comment]
@andyshuxin  I didn't see success messages - this is another issue I posted before: https://github.com/initiumlab/initiumlab.com/issues/78 .
