### ISSUE TITLE
Staging: Built-in Search Engine Cannot Reach the Latest Blog Post about Jackathon

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#80]
<img width="688" alt="screenshot 2015-09-22 at 13 35 12" src="https://cloud.githubusercontent.com/assets/13608119/10011567/f3cef1ca-612e-11e5-9239-51d27c116535.png">
Searched for "book" and "jackathon" but no result.
It seems the latest post hasn't been indexed by the built-in search engine?

**Comment by andyshuxin** [comment]
@frankinit That is expected. The new post is published only to the staging server, which is not accessible to the external search engine we currently use.

**Comment by frankinit** [comment]
cool. I close this issue.
