### ISSUE TITLE
Staging: Hit Area of the Logo on Homepage is Too Large

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#81]
<img width="840" alt="screenshot 2015-09-22 at 13 39 59" src="https://cloud.githubusercontent.com/assets/13608119/10011671/616a7f28-6130-11e5-8e1e-b45a4aaa53b2.png">
When I click blank area <b>around</b> this logo, an image view pops out.

Besides, shall we disable this pop-out behaviour? I think this logo is not supposed to be clickable.

Reference: https://github.com/initiumlab/initiumlab.com/issues/68

**Comment by andyshuxin** [comment]
I noticed this as well. Indeed, the logo should not be enlarged as regular images.
I couldn't find a way to remove the effect and will work on this.

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/1f9a0e2dfe65bc74904ad13e1400f9171763fbc0. The whole lightbox effect is disabled for Lab logo.
