### ISSUE TITLE
Mysterious characters in homepage article part

### ISSUE THREAD

**Issue by yyfjmb** [initiumlab/initiumlab.com#82]
![image](https://cloud.githubusercontent.com/assets/7417451/10011771/25e5fc5a-6132-11e5-84cf-d71806c67bbf.png)

Chrome 45 imac OSX 10.10
not a problem in firefox browser

**Comment by andyshuxin** [comment]
@yyfjmb Does this problem still exist? When you got time, please call me -- I need to examine the details on your computer. Thanks.

**Comment by yyfjmb** [comment]
fixed 
@a935aa9f6a639ed01a1b0c7aaef56b696902ac83
