### ISSUE TITLE
Staging: zoomed-in pic goes out of the phone screen, which needs manual adjustment.

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#83]
![img_1083](https://cloud.githubusercontent.com/assets/14042060/10012345/c55c7906-6139-11e5-8e99-4b509c3b333b.PNG)
 iphone 5s  ios 8.1

**Comment by andyshuxin** [comment]
@Kateliuxue Can't reproduce the problem on my devices? Can you still see this problem on yours?

**Comment by andyshuxin** [comment]
This is iOS8-specific problem.

**Comment by frankinit** [comment]
On iOS 9, Safari auto adjusts the width, but it causes a flash.

**Comment by andyshuxin** [comment]
@frankinit @Kateliuxue 
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/d49c653b481054317e7763242b2c4747d55824c2.

**Comment by Kateliuxue** [comment]
But the zoomed-in picture becomes even much smaller.

**Comment by andyshuxin** [comment]
@Kateliuxue Indeed. Probably should disable lightbox altogether on smaller screens. Please close this issue (which is solved) and open another issue, labelled `enhancement`, about that idea.
cc @yyfjmb @hupili
