### ISSUE TITLE
Staging: Pop-up Box on Home Page Not Responsive on Small Screen and Mobile Phone

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#85]
Img 1: good on regular desktop size.
Img 2: only shows a part on small screen size or mobile phone.
![screenshot 2015-09-22 at 17 19 11](https://cloud.githubusercontent.com/assets/13608119/10014752/118d606a-614e-11e5-9837-cbfd0c1b86dd.png)
![screenshot 2015-09-22 at 17 19 27](https://cloud.githubusercontent.com/assets/13608119/10014784/490193c2-614e-11e5-84f3-0948bc2ca18c.png)

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/43c371567a979d359ff30c4a5e53400e9d2475b6
