### ISSUE TITLE
Staging: Buttons "Home", "About", "Blog" Not Shown on Mobile Phone by Default

### ISSUE THREAD

**Issue by frankinit** [initiumlab/initiumlab.com#86]
I guess it is better to show the three navigation buttons by default, right?

Image 1: By default
Image 2: After click "Menu" Button
![screenshot 2015-09-22 at 18 41 11](https://cloud.githubusercontent.com/assets/13608119/10016438/8fe85ee6-6159-11e5-8626-1bc2851c5d69.png)
![screenshot 2015-09-22 at 18 41 18](https://cloud.githubusercontent.com/assets/13608119/10016436/8fdb2abe-6159-11e5-93cc-14d50c934619.png)

**Comment by andyshuxin** [comment]
@yyfjmb What do you think?

**Comment by andyshuxin** [comment]
1. Remove the hamburger button;
2. The menu bar shows by default.

**Comment by andyshuxin** [comment]
Implemented with https://github.com/initiumlab/hexo-theme-next/commit/ee5aef5e87013564756ff72a186df6783a9aa561

**Comment by Kateliuxue** [comment]
@andyshuxin Looks better now.
