### ISSUE TITLE
Video block not responsive on wechat browser

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#88]
http://initiumlab.com/blog/20150922-jackathon3-review/

Screenshots followed

![850636533_1996008207849915024](https://cloud.githubusercontent.com/assets/1227160/10040616/c4981b66-620f-11e5-86b7-f7425b53b6cb.jpg)

![850636071_1360441690225777090](https://cloud.githubusercontent.com/assets/1227160/10040620/caa06cd4-620f-11e5-99e2-f1d5c6af0fda.jpg)

![850632060_622190227522708053](https://cloud.githubusercontent.com/assets/1227160/10040622/d020616e-620f-11e5-9429-870792677b16.jpg)

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/1c7c871d3afc8683980d55f3a9da90b36bdc76fc
