### ISSUE TITLE
Use sticky footer when content is short

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#89]
<img width="701" alt="screen shot 2015-09-23 at 9 16 13 pm" src="https://cloud.githubusercontent.com/assets/1227160/10045879/56804f76-6238-11e5-9544-b1a476194e54.png">

The footer can be fixed at the page bottom in the above case.

**Comment by andyshuxin** [comment]
Implemented with https://github.com/initiumlab/hexo-theme-next/commit/66d0f7bd5a58a83ac4b01dd2a21e0ffd03cf810a
