### ISSUE TITLE
Add RSS feed on homepage

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#9]

**Comment by andyshuxin** [comment]
@yyfjmb The link is <http://home.initiumlab.com/blog/feed> at this moment, which would change to <initiumlab.com/blog/feed>.
You can use '/blog/feed/' as href.

**Comment by yyfjmb** [comment]
added @andyshuxin

**Comment by yyfjmb** [comment]
need further confirm the button position @andyshuxin

**Comment by andyshuxin** [comment]
@yyfjmb On homepage, let's try putting in footer; otherwise, we can put it on sidebar.
