### ISSUE TITLE
Cannot play videos in Firefox browser.

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#93]

**Comment by frankinit** [comment]
@Kateliuxue Would you please specify your operation system? Browsers work differently on Windows and OS X.

**Comment by Kateliuxue** [comment]
Windows 8.1, Firefox 40.0.3

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/e15b581683eb1582b9091ff3ff7f1e94ff21f2b3. Please check. Thanks.

**Comment by Kateliuxue** [comment]
It works. Thanks.

**Comment by andyshuxin** [comment]
@Kateliuxue If it is confirmed to be solved, please close the issue. Thanks.
