### ISSUE TITLE
"Top" button doesn't work in lightbox page.

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#94]
Windows 8.1   Chrome 43.0/Firefox 40.0

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/hexo-theme-next/commit/5c8fde14e7229a6ab50dd9ceea2007c2aa3d5dab
Please check the staging version. If it's OK, I'll push it to the production server and you could close the issue. Thanks.
