### ISSUE TITLE
Blog Links in The Side Bar Points to Wrong URL "home.initiumlab.com/xxxx" 

### ISSUE THREAD

**Issue by andyshuxin** [initiumlab/initiumlab.com#96]
@frankinit discovered this issue.
![fcbc1b26-63ab-11e5-9981-a0c74f346a41](https://cloud.githubusercontent.com/assets/233354/10098142/6b303678-63b1-11e5-8ed8-a35715e02533.png)
Related to https://github.com/initiumlab/initiumlab.com/issues/59

**Comment by andyshuxin** [comment]
Fixed with https://github.com/initiumlab/initiumlab.com/commit/63b09d533e9f986614914c94b91379de1070ecb5
@frankinit Please check.

**Comment by frankinit** [comment]
Fix confirmed. Thanks.
