### ISSUE TITLE
New blocks in portofolio

### ISSUE THREAD

**Issue by hupili** [initiumlab/initiumlab.com#98]
* [x] salary360. Please link to both wechat version http://salary360wechat.initiumlab.com/?from=initiumlab and facebook version salary360.initiumlab.com/?from=initiumlab   (note the `from` parameters)
* [x] Design collection of Initium Lab. Please pick some representative graphic designs from released articles and use one lightbox to collect image + article link pairs.

**Comment by andyshuxin** [comment]
@yyfjmb Feel free to summon me for help

**Comment by yyfjmb** [comment]
done commit@24b77d8

**Comment by yyfjmb** [comment]
done @hupili  commit@24b77d8ae6ca1310a77712ff4c061381d0fd7748
pull request #106
